imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    use_microseconds: false
    handlers:
        main:
            type:  rotating_file
            level: error
            handler: nested
            max_files: 30
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: warning
        console:
            type: console
            process_psr_3_messages: false
